[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
disallow_untyped_calls = true
check_untyped_defs = true
ignore_missing_imports = true

[tool.black]
target-version = ["py311"]

[tool.isort]
profile = "black"
src_paths = ["game", "tests"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "raise NotImplementedError",
]

[tool.coverage.run]
relative_files = true