[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
disallow_untyped_calls = true
check_untyped_defs = true

[tool.black]
target-version = ["py310"]

[tool.isort]
profile = "black"
src_paths = ["game", "tests"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "raise NotImplementedError",
]